# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cabc4be27dd3b800aaad1840d0876289b87c1727225ff76c2c5933edcf1a132563265833aa47a8f22eaa26501469c5928cfa1cfa92925bae1d1f7331c750ff85

test:
  secret_key_base: 476b9fcb875f99feb9fee1f6cf66781d4fd57dab58de55e1ffc54d40d5591540cd9dc4caddf9194d7e09ca378eec9d47d70037a6cd72710cd399b049fecb461c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
